### ISSUE TITLE
timeout when fetch transifex translations

### ISSUE THREAD

**Issue by Remo** [concrete5/addon_community_translation#8]
Internet and everything is working fine, but half way through the process I get an error and have to start over.  I assume it's not a real problem since we'll most likely only have to run this once, won't we?

```
Working on ru_RU
 - checking Locale entity... created.
 - working on 5.6.2
   > fetching translations for 5.6.2... done.
   > parsing translations... done (3016 strings).
   > fixing plural count (from 4 to 3)... done.
   > saving... done.
 - working on 5.6.2.1
   > fetching translations for 5.6.2.1... done.
   > parsing translations... done (3024 strings).
   > fixing plural count (from 4 to 3)... done.
   > saving... done.
 - working on 5.6.3
   > fetching translations for 5.6.3... Error in cURL request: Connection timed out after 10015 milliseconds
```

**Comment by mlocati** [comment]
Maybe it's a temporary problem of Transifex servers (it wouldn't be the first time). By the way 1. I'll set a longer timeout 2. Yes, it's a tool that will be used just once and 3. You can run the command many times without problems

**Comment by Remo** [comment]
Yes, but it starts from the beginning again and it happens two times, that's went I went to bed ;-)

**Comment by mlocati** [comment]
https://github.com/concrete5/addon_community_translation/commit/454c1bb5e4addec428d2eef8ba9d53898588b388 should fix this

**Comment by Remo** [comment]
still no luck! Whatever I do I get a timeout, I even increased the values to 60 instead of 20.
Well, as long as it runs stable when you import it on the actual server we're fine, otherwise it might have to be incremental.

**Comment by mlocati** [comment]
What about https://github.com/concrete5/addon_community_translation/commit/56a7a6a76428610bfdc39206b4e453cd358bab44 ?

**Comment by Remo** [comment]
I don't think it's a PHP timeout, but let me try that

**Comment by Remo** [comment]
no luck, but I guess we can have a look if it fails on the live server.. I assume we'll never have more than 5 users who actually execute that command.

**Comment by mlocati** [comment]
Well, the `translate:initialize` CLI command is supposed to be run just once, during the switching from transifex to this add on. 
Furthermore,  if this command won't run on the production server we could always use a sql dump of another installation

**Comment by evilaliv3** [comment]
while working on globaleaks i'm also experiencing timeouts on transifex when one does multiple requests.

**Comment by evilaliv3** [comment]
i'm using a custom grunt script done with useragent for that but the issue is the same; connections starts going in timeout.

**Comment by mlocati** [comment]
Me too I notice that sometimes communications with Transifex fail with a timeout... That's another reason to move from Transifex to CommunityTranslation :wink:
